### ISSUE TITLE
[APPENG] Removing recipes in Inscriber throws error

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/Mod-Tweaker2#24]
[Error & Script](http://puu.sh/gqSiT/0f52cc9863.txt)

**Comment by Yulife** [comment]
Still happening. @Voidi?

**Comment by Syer10** [comment]
This is happening in the modpack Regrowth for my friend

**Comment by bookerthegeek** [comment]
Still an issue. AE2 does not like the caching the recipies.
