### ISSUE TITLE
Recovery of Forestry Fixes

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/Mod-Tweaker2#27]
Calling @Voidi. You have done a lot of fixes for Forestry that add new lines in the code. May you sync those in this repository?

**Comment by Voidi** [comment]
Which fixes? can you list them?

**Comment by Voidi** [comment]
Sorry for the long delay, i had work todo in my Modpack.
There was only three small changes that got forgotten.
As soon i have more time, i will began the rewrite part.

**Comment by Yulife** [comment]
Cheers!
