### ISSUE TITLE
Adding Flowers to Bee's Flower Groups

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/Mod-Tweaker2#34]
Due to the flower system being rewritten in Forestry, would it be possible to add certain blocks to certain bee groups? For example the Rocky bees' flowers are rocks, Jungle's fern and vines, etc.
Calling @mezz if this would even be possible.

**Comment by mezz** [comment]
This is possible now.
You can use `IFlowerRegistry` to add flowers.

Here's an example of adding a jungle flower:

```java
IFlowerRegistry flowerRegistry = FlowerManager.flowerRegistry;
flowerRegistry.registerAcceptableFlower(flowerBlock, flowerMeta, FlowerManager.FlowerTypeJungle);
```

To add flowers that are acceptable *and* have the bees grow them, use `IFlowerRegistry.registerPlantableFlower` instead.

To add flowers for bees in Extra Bees and other bee addons, it is the same process. You will need to find the key they use for their flowers (since Forestry wont have it listed like `FlowerManager.FlowerTypeJungle`).

**Comment by Yulife** [comment]
@mezz would you be so kind and hit me up with a list of all of Forestry's flower types? Greatly appreciated.

**Comment by mezz** [comment]
Sure, they're listed in `FlowerManager` here:
https://github.com/ForestryMC/ForestryAPI/blob/3e5b83d1b9331c02db01dc52aebe9bc2e13372b7/forestry/api/apiculture/FlowerManager.java#L29-L37

**Comment by Yulife** [comment]
Thank youuu ~

**Comment by Yulife** [comment]
Alright Voidi, you are the Forestry expert... could you think of a few ways using those groups? @mezz are there "bee" strings for each species? For example you could assign the Tropical Species to the Winter Flowers with the appropriate script.

**Comment by Voidi** [comment]
@mezz how is adding flowers via API different from the existing way via config file?

**Comment by mezz** [comment]
The API is more powerful right now, you can only add `FlowerTypeVanilla` via the config and they will always get planted by bees (there is no option like `registerAcceptableFlower`).

The config will gain similar abilities to the API when this request is implemented: https://github.com/ForestryMC/ForestryMC/issues/536

**Comment by Voidi** [comment]
@Yulife
I would assign low priority to this. 
It doesn't make much sense to implement something in Minetweaker if the mod itself has an config option.

**Comment by Yulife** [comment]
Forestry has a config option for that?... Interesting. Still, some prefer MT over config so it is indeed low-priority. Thanks!
