### ISSUE TITLE
Crash with the latest version

### ISSUE THREAD

**Issue by TheQuantumGeneral** [jaredlll08/Mod-Tweaker2#38]
Using latest Forestry too

http://pastebin.com/JBup3r1M

**Comment by tterrag1098** [comment]
Is that latest forestry? Either this mod isn't updated to use its new API, or you have an outdated forestry.

**Comment by TheQuantumGeneral** [comment]
Forestry 3.6.3.20 release 14th July, latest from Curse is the one i'm using with ModTweaker2 - 0.9.1 current latest from Curse.

**Comment by Yulife** [comment]
Wrong repo. lol
Use the Modtweaker2 repo without the substract letter.
