### ISSUE TITLE
trying to add recipe for Forestry carpenter

### ISSUE THREAD

**Issue by kotoroshinoto** [jaredlll08/Mod-Tweaker2#39]
First I tried
mods.forestry.Carpenter.addRecipe(20, <liquid:creosote> * 1000, [<ore:logWood>, <ore:logWood>, <ore:logWood>, <ore:logWood>, null, <ore:logWood>, <ore:logWood>, <ore:logWood>, <ore:logWood>], null, <Forestry:impregnatedCasing> * 1);

but got a complaint that it couldn't cast an oredict entry to an itemstack.

then I tried this:
for logitem in <ore:logWood>.items {
 mods.forestry.Carpenter.addRecipe(20, <liquid:creosote> * 1000, [logitem, logitem, logitem, logitem, null, logitem, logitem, logitem, logitem], null, <Forestry:impregnatedCasing> * 1);
}

I end up getting "a method available but none matches the parameters"

**Comment by kotoroshinoto** [comment]
the great/less signs got removed, but they're there in the original

**Comment by jaredlll08** [comment]
The Carpenter does not support oredict.

**Comment by kotoroshinoto** [comment]
guess putting in a permuting function would be too much?

**Comment by kotoroshinoto** [comment]
I mean, i know that could be onerous as far as # of recipes that turns into if an entry has a lot in it, but how much time would that computation actually take?

**Comment by jaredlll08** [comment]
no idea honestly :/

**Comment by kotoroshinoto** [comment]
That would get around the issue, could impliment that and just put a caveat that if there are a lot of oredict entries it could introduce a hiccup or two. ;p

Obviously the more graceful solution would be to get the mod author to have it support oredict
